### ISSUE TITLE
Build.sh does not work in Cygwin environment

### ISSUE THREAD

**Issue by kaby76** [cake-build/example#14]
build.sh (https://github.com/cake-build/example/blob/master/build.sh) does not work in Cygwin. This is because path names in Cygwin are a Unix-like syntax e.g., "/cygdrive/c/foobar/". However, mono.exe does not accept these path names. Please use instead relative paths, mono will work with that. If Cygwin is not supported, add to the top a test of uname (http://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux).

**Comment by gep13** [comment]
@kaby76 would you be in a position to add a PR for the latter part of your suggestion? Thanks!
