### ISSUE TITLE
build.ps1 not executing

### ISSUE THREAD

**Issue by VivienRuizFei** [cake-build/example#19]
Hi,

I've tried to execute build.ps1, following the "Getting started" page (http://cakebuild.net/docs/tutorials/getting-started).

It seems to fail on line 50 of build.ps1. First error being:
"Join-Path : cannot bind argument to parameter 'Path' because it is null.

Writing 
`$TOOLS_DIR = Join-Path $PS_Script_Root "tools"`
instead of 
`$TOOLS_DIR = Join-Path $PSScriptRoot "tools"`
allowed the script to execute.

I don't know about powershell or cake, but it looks like it is just the underscores missing, right ?

**Comment by devlead** [comment]
Hi,
$PSScriptRoot is correct, you're probably on an PowerShell version older than 3.0(most current version is 5), which is when it was introduced globally, before null except in modules.

https://technet.microsoft.com/en-us/library/hh847768.aspx

>  _$PSScriptRoot_
> Contains the directory from which a script is being run. 
> 
> In Windows PowerShell 2.0, this variable is valid only in script modules
> (.psm1). Beginning in Windows PowerShell 3.0, it is valid in all scripts.

If you're running PoweShell 2.0 you could probably add something like this:

``` PowerShell
if(!$PSScriptRoot){
    $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent
}
```

But I would recommend if possible to update to newer version of PowerShell as many things has improved in general.

**Comment by gep13** [comment]
@devlead I thought we updated the bootstrapper to work with earlier versions of PowerShell.  Hence why we have this:

https://github.com/cake-build/example/blob/master/build.ps1#L49

Which should account for the lack of that variable in earlier versions.

**Comment by patriksvensson** [comment]
@gep13 We're not using that variable though (just noticed) :(

**Comment by devlead** [comment]
Then we should probably remove that and use this code

``` PowerShell
if(!$PSScriptRoot){
    $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent
}
```

**Comment by VivienRuizFei** [comment]
You are correct, I'm running powershell version 2.0
