### ISSUE TITLE
build.sh downloads old version of nuget

### ISSUE THREAD

**Issue by KyleGobel** [cake-build/example#22]
lots of things just don't work with the nuget 2.8 that's downloaded.

I fixed many issues by actually downloading this version from build.sh

```
https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe
```

I'm not sure if there's a better url to download a 'mono' version of NuGet, but the 2.8 version currently won't cut it for several scenarios

(Maybe a better issue on nuget repo)

**Comment by gep13** [comment]
@KyleGobel this has now been taken care of in the latest version.  Let us know if you run into any further issues.
