### ISSUE TITLE
Make this project build using PowerShell 2.0

### ISSUE THREAD

**Issue by gep13** [cake-build/example#26]
The new plan going forward is to always update this projects bootstrapper when changes are made to the bootstrapper in the resources repository.  In order to keep compatibility with PowerShell 2.0, I think it makes a lot of sense to force our AppVeyor build to use version 2 of PowerShell.  That way, if the build fails, we know we have broken something.

Thoughts @devlead

**Comment by devlead** [comment]
@gep13 agree makes sense, it's just an flag to PowerShell exe to force it into version 2 mode.

**Comment by gep13** [comment]
@devlead yip, that is what I thought.  So I was thinking just to change the appveyor.yml file to use a cmd command, and call powershell from there?

**Comment by devlead** [comment]
@gep13  sounds reasonable👍 Important part is that we get the exit code, so build still fails on failure but that's easy to test with bogus PR afterwards.

**Comment by devlead** [comment]
@gep13 example now builds using PowerShell V2

**Comment by gep13** [comment]
@devlead should we have this in an appveyor.yml file?

**Comment by devlead** [comment]
Don't think we should force people to use PowerShell 2.

**Comment by gep13** [comment]
> @devlead said...
> Don't think we should forcepeople to use PowerShell 2.

Aou lost me.  Are you talking about people forking this repo, and therefore having the same appveyor.yml? Otherwise, I don't see how we would be forcing anyone to do anything.  I was suggesting putting it in our own appveyor.yml file, simply as a reminder that we are doing that, rather than having to go back to the AppVeyor UI.

**Comment by devlead** [comment]
fair point exported and added the config used now.
