### ISSUE TITLE
Running target issue

### ISSUE THREAD

**Issue by constructor-igor** [cake-build/example#28]
Please, could you help me to understand: I defined default target "Report", but when I run the script (see below) Powershell shows error:
![image](https://cloud.githubusercontent.com/assets/1849690/19219106/419a50e0-8e13-11e6-8db8-dfa6dbdf727f.png)

```
var target = Argument("Target", "Report");

Task("Start")
  .Does(() =>
{
  Information("Hello World!");
});

Task("Tests")
    .IsDependentOn("Start")
    .Does(()=>
{
    Information("Tests!");
});

Task("Report")
    .IsDependentOn("Tests")
    .Does(()=>
{
    Information("Report!");
});

RunTarget(target);
```

**Comment by gep13** [comment]
@constructor-igor have a look here: 

https://github.com/cake-build/example/blob/master/build.ps1#L44

If you don't specify a target argument for the build.ps1 the default is Default. As a result, there is not a target called that in your script. Normally, I leave the Default task in place, but instead use an IsDependentOn method call to specify which Target should be invoked when calling Default.

**Comment by constructor-igor** [comment]
but what does it mean `var target = Argument("Target", "Report");` ?
I thought it defines default "Report"

**Comment by gep13** [comment]
It does, when there is no target being passed in. However, the bootstrapper is always passing a target, I.e. Default 🙂

**Comment by constructor-igor** [comment]
ok. understood ;)
thank you,
Igor.
