### ISSUE TITLE
NUnit2: how to define test class

### ISSUE THREAD

**Issue by constructor-igor** [cake-build/example#29]
I need execute single test class from a test .dll. But I cannot find a way to define the test class.
Please, could you help me to define name of test class for nunit2. 
I cannot find answer on the question on http://cakebuild.net/api/cake.common.tools.nunit/6a62c9e4

**Comment by gep13** [comment]
@constructor-igor if you are doing this directly using the nunit console runner, how do you achieve this?

**Comment by constructor-igor** [comment]
I add `/fixture=TestClass`, where TestClass is name of my test class

**Comment by gep13** [comment]
Okay, so looks like we don't expose the Fixture property: http://cakebuild.net/api/cake.common.tools.nunit/6a62c9e4 We would accept a PR to add this in. In the mean time, you could use ArgumentCustomization to add it.

**Comment by constructor-igor** [comment]
Ok. I added **ArgumentCustomization** and it works.

```
NUnit(assemblies, new NUnitSettings { ArgumentCustomization = args=>args.Append("/fixture=TestClass") });
```

thank you.

**Comment by gep13** [comment]
Great! Can I get you to raise an issue on the cake-build/cake repo to add the Fixture Property into the NUnitSettings? Thanks!
