### ISSUE TITLE
DownloadFile is not handling redirections

### ISSUE THREAD

**Issue by serenata-keith-mifsud** [cake-build/example#34]
https://github.com/cake-build/example/blob/226a70b61562aed2227b9eaabb57cd92179e5d5b/build.ps1#L125

http://cakebuild.net/download/bootstrapper/packages is being redirected to https://raw.githubusercontent.com/cake-build/resources/master/packages.config and System.Net.WebClient.DownloadFile does not seem to be able to handle that

**Comment by gep13** [comment]
@serenata-keith-mifsud I have just tested this locally on my machine, and it works as expected.

Do you have any custom configuration/setup that could be preventing this from working?

**Comment by serenata-keith-mifsud** [comment]
No I've only changed the build.cake itself, not the cake.ps1

Can you confirm that the tools folder is empty before running the script?

**Comment by gep13** [comment]
@serenata-keith-mifsud yes, I tried it both as a fresh clone, and by deleting the tools folder, as I noticed that you must have been doing this in order for that part of the bootstrapper to be called at all.

I have just updated this example repository to use the latest recommended bootstrapper, can you please give that a try to see if it helps.

I have to ask though, why are you deleting the tools folder?

**Comment by serenata-keith-mifsud** [comment]
thanks I'll try it out. We have an automated build configuration where it downloads the repo and builds everything with the cake script, thus always having a fresh copy of the repo :)

**Comment by serenata-keith-mifsud** [comment]
I tried it out again and everything seems fine. Thanks :)

**Comment by gep13** [comment]
>@serenata-keith-mifsud said...
thanks I'll try it out. We have an automated build configuration where it downloads the repo and builds everything with the cake script, thus always having a fresh copy of the repo :)

Yes, that makes sense, however, the recommendation, as per what is the case in this repository, is to commit the packages.config file so that you are pinning to a specific version of Cake.  You can find more information about this here: https://cakebuild.net/docs/tutorials/pinning-cake-version

>@serenata-keith-mifsud said...
I tried it out again and everything seems fine. Thanks :)

Ok, so you must have some proxy setup on your system, as this is the only really difference.

**Comment by serenata-keith-mifsud** [comment]
Adding the packages.config does make a lot sense actually. Thank you very much for your quick response 💯 

> Ok, so you must have some proxy setup on your system, as this is the only really difference.

I can't really understand what was happening, the URL was working fine on any browser and changing the URL in the ps1 to https://raw.githubusercontent.com/cake-build/resources/master/packages.config allowed us to run the script. As you said, this seems to have been an issue from our side.

**Comment by gep13** [comment]
Your browser will likely be automatically configured to use the proxy that you have.  However, when doing a raw HTTP request from a script, the default is NOT to respect the proxy configuration.  In the latest bootstrapper which I just added to this repository, it now attempts to use the proxy if there.

**Comment by serenata-keith-mifsud** [comment]
Ah perfect :)
