### ISSUE TITLE
build.sh - passing argument with value doesn't work

### ISSUE THREAD

**Issue by paweljasinski** [cake-build/example#43]
e.g. 
```
./build.sh -c Debug
```
fails with an error
```
More than one build script specified.
For usage, use parameter --help
```

Reported: https://gist.github.com/tiesmaster/486756281d2631d3c1828a22ca77804e

**Comment by nils-a** [comment]
With the release of Cake 2.0.0-rc0001 we no longer ship the Cake.exe runner. #58 changed this example to use the bootstrapper for the Cake tool, so all arguments are passed to Cake exactly as specified on the command line.
