### ISSUE TITLE
build.sh doesn't work on systems without mono

### ISSUE THREAD

**Issue by paweljasinski** [cake-build/example#44]
when build.sh is used under cygwin it tries to use mono which fails

**Comment by gep13** [comment]
@paweljasinski I am not a user of cygwin, so I can't replicate this, but if you run cake.exe under cygwin does it actually run?

**Comment by paweljasinski** [comment]
yes

**Comment by nils-a** [comment]
With the release of Cake 2.0.0-rc0001 we no longer ship the Cake.exe runner. #58 changed this example to use the bootstrapper for the Cake tool, so mono is no longer a requirement.
