### ISSUE TITLE
Calling build.sh with -Target argument causes double targets

### ISSUE THREAD

**Issue by kanadaj** [cake-build/example#49]
Due to `-target=$TARGET $DRYRUN "${SCRIPT_ARGUMENTS[@]}"`, the script seems to pass both "Default" and the actual target argument of the call which then returns the following error:
```
Multiple arguments with the same name (Target).
```

This happened while running in a docker container from ```pomma89/dotnet-mono:dotnet-3-mono-5-sdk``` which runs some version of Debian I believe and the simple call
```sh
RUN ./build.sh -Target=Clean
```
.

**Comment by lassana** [comment]
Any workaround?
UPD: you probably need smth like this: `./build.sh --target UpdateBinding`

**Comment by kanadaj** [comment]
I think I ended up mounting a custom build.sh file with the original target argument removed so it's simply `$DRYRUN "${SCRIPT_ARGUMENTS[@]}"`

**Comment by nils-a** [comment]
https://github.com/cake-build/example/pull/58 introduced the usage of the newest bootstrapper, so this issue should no longer occur.
