### ISSUE TITLE
-target in build.ps1

### ISSUE THREAD

**Issue by EdgardosReis** [cake-build/example#56]
https://github.com/cake-build/example/blob/0a34b48b8b8b3b4ac946f0915c2d62fdb51191ea/build.ps1#L222

Shouldn't this be changed because of the new version 1.0.0? from -target to --target

https://cakebuild.net/docs/getting-started/upgrade#cake-cli-updates

**Comment by devlead** [comment]
Hi! Yes, it should - well spotted. Are you in a position to send a pull request?

**Comment by EdgardosReis** [comment]
yes sure, I'll do it later today.

**Comment by devlead** [comment]
Excellent 👍

**Comment by EdgardosReis** [comment]
#57 merged
